/* 
PRODUTO COMANDA

VIEWS
	FORNECEDOR - PRODUTO - ESTOQUE
	CLIENTE - PRODUTO - ESTOQUE
	ESTABELECIMENTO - FUNCIONARIOS
	NIVELH - LOGIN
 
 FIQUEI COM PREGUIÇA DE ALTERAR EM CIMA DO SEU, ENTÃO CRIEI UM OUTRO SCRIPT NO FIM DA PÁGINA
*/
USE MASTER;
GO
DROP DATABASE DB_LEO;
GO
CREATE DATABASE DB_LEO;
GO
USE DB_LEO;
GO

/*=================================================
				ESTABELECIMENTO
===================================================*/
 
CREATE TABLE ESTABELECIMENTO (
	 ID UNIQUEIDENTIFIER, -- ESSE SERÁ OS IDS DE RELACIONAMENTO DE TODAS AS TABELAS
     --CNPJ_ESTABELECIMENTO VARCHAR(16) UNIQUE NOT NULL , -- CNPJ NÃO PODE SER INT, JÁ QUE O FORMATO DELE PODE VIR FORMATADO(COM PONTOS) OU CASO VENHA COMO NÚMERO, SERÁ GRANDE DEMAIS PARA A MEMÓRIA AGUENTAR
     --NOME_ESTABELECIMENTO VARCHAR(20) NOT NULL ,
);
GO
  
/*=================================================
					PRODUTO
===================================================*/

CREATE TABLE PRODUTO (
	COD_PRODUTO INT IDENTITY PRIMARY KEY NOT NULL,
    NOME VARCHAR(85),    
    VALOR_UNIT DECIMAL(10,2),
    MARCA VARCHAR(15),
    PRODUTO_TIPO VARCHAR(20)
);
GO 

CREATE TABLE ESTOQUE_PRODUTO (
    COD_ESTOQUE INT IDENTITY(1,1) PRIMARY KEY NOT NULL ,
    COD_PRODUTO INT,	
	QUANTIDADE INT,  
    CNPJ_ESTABELECIMENTO INT,
	CONSTRAINT FK_COD_ESTABELECIMENTO_P FOREIGN KEY (CNPJ_ESTABELECIMENTO)REFERENCES ESTABELECIMENTO (CNPJ_ESTABELECIMENTO),
	CONSTRAINT FK_ESTOQUE_COD_PRODUTO FOREIGN KEY ( COD_PRODUTO)REFERENCES PRODUTO (COD_PRODUTO)
);
GO

    
/*=================================================
					CONSUMIDOR
===================================================*/

CREATE TABLE CONSUMIDOR(  
	ID_CONSUMIDOR INT  PRIMARY KEY  IDENTITY(1,1)NOT NULL,
	NOME VARCHAR(30) NOT NULL,
    SEXO CHAR NOT NULL,    
    EMAIL VARCHAR(50),    
    USUARIO VARCHAR(16),
    SENHA VARCHAR(20),    
);
GO
  
 /*=================================================
					FUNCIONARIO
===================================================*/

CREATE TABLE FUNCIONARIO (
    ID_FUNC INT IDENTITY(1,1) PRIMARY KEY NOT NULL,  
    NOME VARCHAR(20) NOT NULL,
    SEXO CHAR NOT NULL,
    DATA_DE_NASCIMENTO DATETIME NOT NULL,
    CARGO VARCHAR(20) NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    CPF CHAR(11) NOT NULL,
    EMAIL VARCHAR(50),
    USUARIO VARCHAR(20),
    CNPJ_ESTABELECIMENTO INT NOT NULL,
	CONSTRAINT FK_ESTABELECIMENTO_COD_ESTABELECIMENTO FOREIGN KEY (CNPJ_ESTABELECIMENTO)REFERENCES ESTABELECIMENTO(CNPJ_ESTABELECIMENTO)
);
GO
 
 /*=================================================
				 FORNECEDOR
===================================================*/

CREATE TABLE FORNECEDOR (
	CNPJ_FORNECEDOR INT PRIMARY KEY NOT NULL,
    NOME VARCHAR(25),
    SEXO CHAR,
    CPF VARCHAR(11),
	FK_COD_PRODUTO INT,
	CONSTRAINT FK_COD_PRODUTO FOREIGN KEY (FK_COD_PRODUTO)REFERENCES PRODUTO(COD_PRODUTO)
 );
GO
 
/*=================================================
					COMANDA
===================================================*/

CREATE TABLE COMANDA (
    NUM_COMANDA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,    
    ID_COMANDA INT NOT NULL,
    VALOR_TOTAL DECIMAL(10,2),
    CNPJ_ESTABELECIMENTO INT,
	FK_COD_PRODUTO INT,
	CONSTRAINT FK_COD_ESTABELECIMENTO_C FOREIGN KEY (CNPJ_ESTABELECIMENTO)REFERENCES ESTABELECIMENTO(CNPJ_ESTABELECIMENTO),
	CONSTRAINT FK_COMANDA_COD_PRODUTO FOREIGN KEY (FK_COD_PRODUTO)REFERENCES PRODUTO(COD_PRODUTO)
);
GO
  
/*=================================================
					PEDIDO
===================================================*/

CREATE TABLE PEDIDO (
    NUM_PEDIDO INT IDENTITY(1,1) PRIMARY KEY, 
    DATA_PEDIDO DATE,
    NOME_PRODUTO VARCHAR(35),
    QUANTIDADE INT,
    VALOR_UNIT DECIMAL(10,2),
    FK_ID_CONSUMIDOR_P INT,
	FK_COD_PRODUTO INT,
	CONSTRAINT FK_ID_CONSUMIDOR_P FOREIGN KEY (FK_ID_CONSUMIDOR_P)REFERENCES CONSUMIDOR(ID_CONSUMIDOR),	
	CONSTRAINT FK_PED_COD_PRODUTO FOREIGN KEY (FK_COD_PRODUTO)REFERENCES PRODUTO(COD_PRODUTO)
);
GO 
/*=================================================
					HIERARQUIA
===================================================*/

 








CREATE TABLE TB_PAD_INF_PESSOAL(
	ID			UNIQUEIDENTIFIER,
	TIPO_PESS	UNIQUEIDENTIFIER, -- FK DA TABELA TB_PAD_TIPO_PESSOA
	CPF_CNPJ	VARCHAR(16) UNIQUE,
	NOME		VARCHAR(50), 
);
CREATE TABLE TB_LOGIN(
	ID		UNIQUEIDENTIFIER, 
	PESSOA	UNIQUEIDENTIFIER,
	USUARIO VARCHAR(30) UNIQUE NOT NULL,
	SENHA VARCHAR(20) NOT NULL, 
	 
);
CREATE TABLE TB_PAD_TIPO_PESSOA(
	ID			UNIQUEIDENTIFIER,
	DESCRICAO	VARCHAR(50)
);

CREATE TABLE TB_PAD_TELEFONE(
	ID			UNIQUEIDENTIFIER,
	PESSOA		UNIQUEIDENTIFIER, -- FK DA TABELA TB_PAD_INF_PESSOAL
	TELEFONE	VARCHAR(14) UNIQUE,
	ATIVO		BIT,			-- TRUE OU FALSE PARA SABER SE O TELEFONE AINDA É USADO
);
CREATE TABLE TB_PAD_ENDERECO(
	ID			UNIQUEIDENTIFIER,
	PESSOA		UNIQUEIDENTIFIER, -- FK DA TABELA TB_PAD_INF_PESSOAL
	CEP			CHAR(6) UNIQUE,	 -- PODE CRIAR UMA TABELA DE CEPS, ONDE CONTÉM TODOS OS CEPS DE BARUERI, JÁ EXISTEM PLANILHAS ONLINE PARA ISSO
	ATIVO		BIT,			-- TRUE OU FALSE PARA SABER SE O TELEFONE AINDA É USADO
);

CREATE TABLE TB_PAD_PRODUTO( 
-- SÓ SERÁ INSERIDO UM UNICO PRODUTO AQUI EX.: SE A PADARIA COMPROOU 20 PÃES, SÓ IRÁ SER INSERIDO UM AQUI 
	ID			UNIQUEIDENTIFIER,
	DESCRICAO	VARCHAR(70),
	/*
	FICA A CRITÉRIO DO GRUPO ADICIONAR COISAS COMO 
	MODELO, MARCA, ETC
	*/
	VALOR		DECIMAL(6,2)
);
CREATE TABLE TB_PAD_LISTA_PRODUTO(
	ID			UNIQUEIDENTIFIER,
	PRODUTO		UNIQUEIDENTIFIER,
	SITUACAO	INT, -- 1 => ESTOQUE, 2 => VENDIDO, 3 => PERDIDO
);

 
CREATE TABLE TB_PAD_ESTOQUE(
	ID				UNIQUEIDENTIFIER,
	PESS_ESTAB		UNIQUEIDENTIFIER,	-- AQUI O NOME É APENAS PARA MANTER O PADRAO, MAS SÓ ENTRARÃO OS ESTABELECIMENTOS NESSA TABELA (DÁ PRA SABER SE É UM ESTABELECIMENTO PELO TIPO DE PESSOA)
	PESS_FORN		UNIQUEIDENTIFIER,	-- ESSE CAMPO TAMBÉM VEM DA TABELA DE PESSOA, MAS SÓ ENTRARÃO OS FORNECEDORES DE CADA PRODUTO
	PRODUTO			UNIQUEIDENTIFIER,
	QUANTIDADE_MIN	INT,			-- CADA PRODUTO TEM A PARTICULARIDADE DE UMA QUANTIDADE MINIMA PARA SER S
	-- NÃO TEM A QUANTIDADE DE PRODUTOS DENTRO DO ESTOQUE PORQUE ISSO É POSSIVEL CALCULAR POR MEIO DE UM COUNT DENTRO DA TABELA DE PRODUTO
);

CREATE TABLE TB_PAD_COMANDA (
    ID				UNIQUEIDENTIFIER,
    PESSOA			UNIQUEIDENTIFIER, -- ESTABELECIMENTO  
	NUMERO			INT UNIQUE,			-- NUMERO QUE FICA EXPOSTO NA COMANDA PARA CONTROLE VISUAL
); 

CREATE TABLE TB_PAD_LISTA_COMANDA(
	ID				UNIQUEIDENTIFIER,
	COMANDA			UNIQUEIDENTIFIER, -- TABELA DE COMANDA
	PRODUTO			UNIQUEIDENTIFIER, -- TABELA DE LISTA_PRODUTO
	SITUACAO		INT,				-- 1 => COMANDA EM ABERTO, 2 => PAGA
);

-- PARA PEDIDOS, É MAIS PRATICO ABRIR UMA NOVA COMANDA E CONTROLAR O PROCESSO POR ELA, PORÉM CASO NÃO QUEIRA
-- É SÓ REPETIR O MESMO PROCESSO QUE FOI FEITO NA COMANDA. CRIAR UMA TABELA LISTA_PEDIDO E ADICIONAR O ID DO PEDIDO E 
-- IR ADICIONANDO CADA PRODUTO DO ESOTOQUE DENTRO DO PEDIDO
CREATE TABLE TB_PAD_PEDIDO (
	ID				UNIQUEIDENTIFIER,
	COMANDA			UNIQUEIDENTIFIER, -- CASO QUEIRA OPTAR PELA OPÇÃO DE CONTROLAR PELA COMANDA; CASO NÃO QUEIRA, TIRE ESSE CAMPO
	PESSOA			UNIQUEIDENTIFIER,
	DATA_PEDIDO		DATE,
	SITUACAO		INT,			--  1 => EM ABERTO, 2=> PAGO E A CAMINHO, 3 => ENTREGUE
);





















