/* 
PRODUTO COMANDA

VIEWS
	FORNECEDOR - PRODUTO - ESTOQUE
	CLIENTE - PRODUTO - ESTOQUE
	ESTABELECIMENTO - FUNCIONARIOS
	NIVELH - LOGIN
 

*/
USE MASTER;
GO
DROP DATABASE AGORA_V3;
GO
CREATE DATABASE AGORA_V3;
GO
USE AGORA_V3;
GO

/*=================================================
				ESTABELECIMENTO
===================================================*/
 
CREATE TABLE ESTABELECIMENTO (
     CNPJ_ESTABELECIMENTO INT PRIMARY KEY NOT NULL ,
     NOME_ESTABELECIMENTO VARCHAR(20) NOT NULL ,
);
GO

CREATE TABLE ENDERECO_EST(	 
	ID_END INT IDENTITY(1,1) PRIMARY KEY NOT NULL , 
	RUA VARCHAR(50) ,
	CEP CHAR(9) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
	FK_COD_ESTABELECIMENTO INT,
	CONSTRAINT FK_COD_ESTABELECIMENTO FOREIGN KEY (FK_COD_ESTABELECIMENTO) REFERENCES ESTABELECIMENTO(CNPJ_ESTABELECIMENTO)
);
GO


/*=================================================
					PRODUTO
===================================================*/

CREATE TABLE PRODUTO (
	COD_PRODUTO INT IDENTITY PRIMARY KEY NOT NULL,
    NOME VARCHAR(85),    
    VALOR_UNIT DECIMAL(10,2),
    MARCA VARCHAR(15),
    PRODUTO_TIPO VARCHAR(20)
);
GO



CREATE TABLE ESTOQUE_PRODUTO (
    COD_ESTOQUE INT IDENTITY(1,1) PRIMARY KEY NOT NULL ,
    COD_PRODUTO INT,	
	QUANTIDADE INT,  
    CNPJ_ESTABELECIMENTO INT,
	CONSTRAINT FK_COD_ESTABELECIMENTO_P FOREIGN KEY (CNPJ_ESTABELECIMENTO)REFERENCES ESTABELECIMENTO (CNPJ_ESTABELECIMENTO),
	CONSTRAINT FK_ESTOQUE_COD_PRODUTO FOREIGN KEY ( COD_PRODUTO)REFERENCES PRODUTO (COD_PRODUTO)
);
GO

  
/*=================================================
					CONSUMIDOR
===================================================*/

CREATE TABLE CONSUMIDOR(  
	ID_CONSUMIDOR INT  PRIMARY KEY  IDENTITY(1,1)NOT NULL,
	NOME VARCHAR(30) NOT NULL,
    SEXO CHAR NOT NULL,    
    EMAIL VARCHAR(50),    
    USUARIO VARCHAR(16),
    SENHA VARCHAR(20),    
);
GO

CREATE TABLE ENDERECO_CONS(
    ID_END INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    RUA VARCHAR(30) ,
    CIDADE VARCHAR(20) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    NUMERO VARCHAR(4) NOT NULL,
    COMPLEMENTO VARCHAR(15) NOT NULL,
	FK_ID_CONSUMIDOR INT,
	CONSTRAINT FK_END_ID_CONSUMIDOR FOREIGN KEY(FK_ID_CONSUMIDOR) REFERENCES CONSUMIDOR(ID_CONSUMIDOR)
);
GO

CREATE TABLE TELEFONE_CONS(
    ID_TEL INT PRIMARY KEY IDENTITY(1,1) NOT NULL ,   
    NUM_TELEFONE VARCHAR(14) NOT NULL,
	ID_CONSUMIDOR INT,
	CONSTRAINT FK_TEL_ID_CONSUMIDOR FOREIGN KEY(ID_CONSUMIDOR) REFERENCES CONSUMIDOR(ID_CONSUMIDOR)
);
GO

 
 /*=================================================
					FUNCIONARIO
===================================================*/

CREATE TABLE FUNCIONARIO (
    ID_FUNC INT IDENTITY(1,1) PRIMARY KEY NOT NULL,  
    NOME VARCHAR(20) NOT NULL,
    SEXO CHAR NOT NULL,
    DATA_DE_NASCIMENTO DATETIME NOT NULL,
    CARGO VARCHAR(20) NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    CPF CHAR(11) NOT NULL,
    EMAIL VARCHAR(50),
    USUARIO VARCHAR(20),
    CNPJ_ESTABELECIMENTO INT NOT NULL,
	CONSTRAINT FK_ESTABELECIMENTO_COD_ESTABELECIMENTO FOREIGN KEY (CNPJ_ESTABELECIMENTO)REFERENCES ESTABELECIMENTO(CNPJ_ESTABELECIMENTO)
);
GO

CREATE TABLE TELEFONE_FUNC (
	ID_TEL INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NUM_TELEFONE CHAR(13),    
    FK_ID_FUNC INT NOT NULL,
	CONSTRAINT FK_TEL_ID_FUNC FOREIGN KEY (FK_ID_FUNC)REFERENCES FUNCIONARIO(ID_FUNC)
);

CREATE TABLE ENDERECO_FUNC (
    ID_END INT IDENTITY(1,1) PRIMARY KEY NOT NULL , 
	RUA VARCHAR(50),
 	CEP CHAR(9) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
	FK_ID_FUNC INT, 
	CONSTRAINT FK_END_ID_FUNC FOREIGN KEY (FK_ID_FUNC)REFERENCES FUNCIONARIO(ID_FUNC )
);
GO


 /*=================================================
				 FORNECEDOR
===================================================*/

CREATE TABLE FORNECEDOR (
	CNPJ_FORNECEDOR INT PRIMARY KEY NOT NULL,
    NOME VARCHAR(25),
    SEXO CHAR,
    CPF VARCHAR(11),
	FK_COD_PRODUTO INT,
	CONSTRAINT FK_COD_PRODUTO FOREIGN KEY (FK_COD_PRODUTO)REFERENCES PRODUTO(COD_PRODUTO)
 );
GO

CREATE TABLE ENDERECO_FORNECEDOR (
    ID_END INT IDENTITY(1,1) PRIMARY KEY NOT NULL , 
	RUA VARCHAR(50)  ,
 	CEP CHAR(9) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
	CNPJ_FORNECEDOR INT, 
	CONSTRAINT FK_END_ID_FORN FOREIGN KEY (CNPJ_FORNECEDOR)REFERENCES FORNECEDOR(CNPJ_FORNECEDOR)
);
GO

CREATE TABLE TELEFONE_FORNECEDOR (
	ID_TEL INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NUM_TELEFONE CHAR(13),    
    CNPJ_FORNECEDOR INT NOT NULL,
	CONSTRAINT FK_TEL_ID_FORN FOREIGN KEY (CNPJ_FORNECEDOR)REFERENCES FORNECEDOR(CNPJ_FORNECEDOR)
);
GO


/*=================================================
					COMANDA
===================================================*/

CREATE TABLE COMANDA (
    NUM_COMANDA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,    
    ID_COMANDA INT NOT NULL,
    VALOR_TOTAL DECIMAL(10,2),
    CNPJ_ESTABELECIMENTO INT,
	FK_COD_PRODUTO INT,
	CONSTRAINT FK_COD_ESTABELECIMENTO_C FOREIGN KEY (CNPJ_ESTABELECIMENTO)REFERENCES ESTABELECIMENTO(CNPJ_ESTABELECIMENTO),
	CONSTRAINT FK_COMANDA_COD_PRODUTO FOREIGN KEY (FK_COD_PRODUTO)REFERENCES PRODUTO(COD_PRODUTO)
);
GO
 
/*=================================================
					PEDIDO
===================================================*/

CREATE TABLE PEDIDO (
    NUM_PEDIDO INT IDENTITY(1,1) PRIMARY KEY, 
    DATA_PEDIDO DATE,
    NOME_PRODUTO VARCHAR(35),
    QUANTIDADE INT,
    VALOR_UNIT DECIMAL(10,2),
    FK_ID_CONSUMIDOR_P INT,
	FK_COD_PRODUTO INT,
	CONSTRAINT FK_ID_CONSUMIDOR_P FOREIGN KEY (FK_ID_CONSUMIDOR_P)REFERENCES CONSUMIDOR(ID_CONSUMIDOR),	
	CONSTRAINT FK_PED_COD_PRODUTO FOREIGN KEY (FK_COD_PRODUTO)REFERENCES PRODUTO(COD_PRODUTO)
);
GO        
     
    GO

/*=================================================
					HIERARQUIA
===================================================*/

CREATE TABLE TB_NIVERHIERARQUI(
	ID_NH INT PRIMARY KEY IDENTITY(1,1),
	NOME_NH VARCHAR(20)
);
GO


CREATE TABLE TB_LOGIN(
	ID_LOGIN INT PRIMARY KEY IDENTITY(1,1),
	USUARIO VARCHAR(30) UNIQUE NOT NULL,
	SENHA VARCHAR(20) NOT NULL,
	ID_NH INT NOT NULL,
	CONSTRAINT FK_ID_NH FOREIGN KEY (ID_NH) REFERENCES TB_NIVERHIERARQUI(ID_NH)
);
GO


