/*
		SELECT * FROM [dbo].[TB_COMANDA]
		SELECT * FROM [dbo].[TB_CONTATO]
		SELECT * FROM [dbo].[TB_CLIENTES]
		SELECT * FROM [dbo].[TB_ENDERECO]
		SELECT * FROM [dbo].[TB_ESTABELECIMENTOS]
		SELECT * FROM [dbo].[TB_ESTOQUE] 
		SELECT * FROM [dbo].[TB_FUNCIONARIOS]
		SELECT * FROM [dbo].[TB_PRINCIPAL_PESSOA]
		SELECT * FROM [dbo].[TB_HIERARQUIA]
		SELECT * FROM [dbo].[TB_LISTA_PRODUTOS]
		SELECT * FROM [dbo].[TB_LOGIN]
		SELECT * FROM [dbo].[TB_PRODUTOS]
		SELECT * FROM [dbo].[VW_FUNCIONARIO_COMPLETO]
		PROCEDURE CADASTRO_FUNCIONARIO
		Obs: tirei fornecedores por falta de utilidade
*/ 	

USE MASTER;
GO
DROP DATABASE AGORA_V5;
GO
CREATE DATABASE AGORA_V5;
GO
USE AGORA_V5;

CREATE TABLE TB_HIERARQUIA(
		ID INT IDENTITY(1,1) PRIMARY KEY,
		DESCRICAO VARCHAR(30),
);
GO
		INSERT INTO TB_HIERARQUIA VALUES('ADMINISTRADOR');
		INSERT INTO TB_HIERARQUIA (DESCRICAO) VALUES('CAIXA');
		INSERT INTO TB_HIERARQUIA (DESCRICAO) VALUES('BALCONISTA');

CREATE TABLE TB_PRINCIPAL_PESSOA(
	ID		UNIQUEIDENTIFIER,
	TIPO	VARCHAR(20)
);
GO

CREATE TABLE TB_LOGIN(
	ID				INT IDENTITY(1,1) PRIMARY KEY,
	USUARIO			VARCHAR(20) UNIQUE,
	SENHA			VARCHAR(20),
	ID_HIERARQUIA	INT, 
	LOGIN_ID		INT,
	CONSTRAINT ID_HIERARQUIA FOREIGN KEY (ID_HIERARQUIA) REFERENCES TB_HIERARQUIA(ID),
	CONSTRAINT LOGIN_ID FOREIGN KEY (LOGIN_ID) REFERENCES TB_PRINCIPAL_PESSOA(ID)

); 
GO

CREATE TABLE TB_CLIENTES(
	ID	INT PRIMARY KEY IDENTITY(1,1),
	NOME	VARCHAR(80),
	RG	VARCHAR(13),
	CPF	 VARCHAR(15) UNIQUE,
	DT_NASC	 DATETIME,
    SEXO	CHAR(1) CHECK(SEXO ='M'OR SEXO='F') DEFAULT 'M',   
	CLI_ID		INT,
	CONSTRAINT CLI_ID FOREIGN KEY (CLI_ID) REFERENCES TB_PRINCIPAL_PESSOA(ID)

);
GO
 

CREATE TABLE TB_FUNCIONARIOS(
	ID			INT PRIMARY KEY IDENTITY(1,1), 
	NOME		VARCHAR(80),
	RG			VARCHAR(13), --UNIQUE,
	CPF			VARCHAR(15), --UNIQUE,
	CARGO		VARCHAR(20),
	DT_NASC		DATETIME,
    SEXO		CHAR(1) CHECK(SEXO ='M'OR SEXO='F') DEFAULT 'M', 
	FUNC_ID		INT,
	CONSTRAINT FUNC_ID FOREIGN KEY (FUNC_ID) REFERENCES TB_PRINCIPAL_PESSOA(ID)
);	
GO
 

CREATE TABLE TB_ESTABELECIMENTOS(
	ID		INT IDENTITY(1,1) PRIMARY KEY,
	CNPJ    VARCHAR(20),
	NOME_FANTASIA VARCHAR(50),
	ESTAB_ID INT,
	CONSTRAINT ESTAB_ID FOREIGN KEY (ESTAB_ID) REFERENCES TB_PRINCIPAL_PESSOA(ID)

);
GO

CREATE TABLE TB_PRODUTOS(
	ID		INT IDENTITY(1,1) PRIMARY KEY,
	DESCRICAO VARCHAR(50),
	VALOR_COMPRA_UNIDADE DECIMAL(6,2),
	VALOR_VENDA_UNIDADE DECIMAL(6,2),
	ID_ESTABELECIMENTO INT ,
	CONSTRAINT ID_ESTABELECI_PRODUT FOREIGN KEY (ID_ESTABELECIMENTO) REFERENCES TB_ESTABELECIMENTOS(ID)
);
GO

CREATE TABLE TB_ESTOQUE(
	ID		INT IDENTITY(1,1) PRIMARY KEY,
	PRODUTOS VARCHAR(50),
	VALOR_UNI  DECIMAL(5,2),
	QUANTIDADE INT,
	ID_ESTABELECIMENTO INT,
	PROD_ID INT,
	CONSTRAINT ID_ESTABELECIMENTO FOREIGN KEY (ID_ESTABELECIMENTO)REFERENCES TB_ESTABELECIMENTOS(ID),
	CONSTRAINT PROD_ID FOREIGN KEY (PROD_ID)REFERENCES TB_PRODUTOS(ID)
);
GO

CREATE TABLE TB_COMANDA(
	ID		INT IDENTITY(1,1) PRIMARY KEY,
	ID_ESTABELECIMENTO DATE,
	CONSTRAINT ID_ESTABELE_COMAND FOREIGN KEY (ID_ESTABELECIMENTO) REFERENCES TB_ESTABELECIMENTOS(ID)
);
GO

CREATE TABLE TB_PEDIDO(
	ID		INT IDENTITY(1,1) PRIMARY KEY,
	PRODUTO VARCHAR(50),
	QUANTIDADE INT,
	VALOR_UNI DECIMAL(6,2),	
	ID_COMANDA INT,
	ID_PRODUTOS INT,
	CONSTRAINT ID_COMANDA FOREIGN KEY (ID_COMANDA) REFERENCES TB_COMANDA(ID),
	CONSTRAINT ID_PRODUTOS FOREIGN KEY (ID_PRODUTOS) REFERENCES TB_PRODUTOS(ID),
);
GO

CREATE TABLE TB_CONTATO(
	ID		INT IDENTITY(1,1) PRIMARY KEY,
	NUMERO VARCHAR(14) UNIQUE,
	ATIVO BIT,
	CEL_ID INT,
	CONSTRAINT CEL_ID FOREIGN KEY (CEL_ID) REFERENCES TB_PRINCIPAL_PESSOA(ID)
);
GO

CREATE TABLE TB_ENDERECO(
	ID		INT IDENTITY(1,1) PRIMARY KEY,
	CEP		CHAR(9),
	RUA		VARCHAR(100),
	NUMERO	VARCHAR(5),
	BAIRRO	VARCHAR(30),
	ESTADO  VARCHAR(20),
	CIDADE  VARCHAR(30),
	END_ID INT ,
	CONSTRAINT END_ID FOREIGN KEY (END_ID) REFERENCES TB_PRINCIPAL_PESSOA(ID)

);
GO

/*=============================================================
					PROCEDURES
=============================================================*/
CREATE PROCEDURE CADASTRO_FUNCIONARIO
	@ACAO INT,     -- 0 = EXCLUIR,  1= INSERIR,  2= ALTERAR
	@ID INT  = NULL,
	@NOME VARCHAR(80) = NULL,
	@RG VARCHAR(13) = NULL,
	@CPF VARCHAR(15) = NULL,
	@CARGO VARCHAR(20) = NULL,
	@DT_NASC DATETIME = NULL,
	@SEXO CHAR(1) = NULL
AS
	BEGIN
		IF(@ACAO = 0) -- EXCLUIR
			
			BEGIN
				
				DELETE FROM TB_FUNCIONARIOS
						WHERE ID = @ID									
		
				SELECT @ID	AS RETORNO
			END
		ELSE IF(@ACAO = 1)  --INSERIR
			BEGIN
				INSERT INTO TB_FUNCIONARIOS (NOME,RG,CPF,CARGO, DT_NASC,SEXO) VALUES( @NOME,@RG,@CPF,@CARGO,@DT_NASC,@SEXO)
				
				SELECT @@IDENTITY AS RETORNO
			END
		ELSE IF(@ACAO = 2) -- ALTERAR			
			BEGIN
				UPDATE TB_FUNCIONARIOS
				SET NOME = @NOME,
					RG	 = @RG,
					CPF	 = @CPF,
					CARGO = @CARGO,
					DT_NASC	= @DT_NASC,
					SEXO    = @SEXO
				WHERE ID    = @ID

			--	SELECT @ID	AS RETORNO
			END
		ELSE
			BEGIN
				 RAISERROR('ACAO NAO IMPLEMENTADA',16,1);
			END
	END
GO

/*=============================================================
					VIEWS
=============================================================*/

CREATE VIEW VW_FUNCIONARIO_COMPLETO
AS
	SELECT 
		TB_PRINCIPAL_PESSOA.ID,
		TB_FUNCIONARIOS.NOME,
		TB_FUNCIONARIOS.RG,
		TB_FUNCIONARIOS.CPF,
		TB_FUNCIONARIOS.CARGO,
		TB_FUNCIONARIOS.DT_NASC,  
		TB_FUNCIONARIOS.SEXO,
		CEP,
		RUA,
		CIDADE,
		BAIRRO,
		TB_ENDERECO.NUMERO,
		ESTADO,
		TB_CONTATO.NUMERO AS CELULAR,
		ATIVO,
		TB_LOGIN.USUARIO,
		SENHA,
		ID_HIERARQUIA AS HIERARQUIA

	FROM
		TB_FUNCIONARIOS 
			INNER JOIN TB_PRINCIPAL_PESSOA ON TB_PRINCIPAL_PESSOA.ID = TB_FUNCIONARIOS.FUNC_ID
			INNER JOIN TB_ENDERECO ON TB_FUNCIONARIOS.FUNC_ID = TB_ENDERECO.END_ID
			INNER JOIN TB_CONTATO ON TB_FUNCIONARIOS.FUNC_ID = TB_CONTATO.CEL_ID
			INNER JOIN TB_LOGIN ON TB_FUNCIONARIOS.FUNC_ID = TB_LOGIN.LOGIN_ID;
GO
