/* 
PRODUTO COMANDA
VIEWS
	FORNECEDOR - PRODUTO - ESTOQUE
	CLIENTE - PRODUTO - ESTOQUE
	ESTABELECIMENTO - FUNCIONARIOS
	NIVELH - LOGIN

*/
USE MASTER;
GO
DROP DATABASE AGORA_V4;
GO
CREATE DATABASE AGORA_V4;
GO
USE AGORA_V4;
GO

/*=================================================
				ESTABELECIMENTO
===================================================*/
 
 CREATE TABLE TB_TIPO_PESSOA(
	ID			UNIQUEIDENTIFIER PRIMARY KEY,
	DESCRICAO	VARCHAR(100),
 );
 GO

	INSERT INTO TB_TIPO_PESSOA VALUES (NEWID(),'ESTABELECIMENTO');
	INSERT INTO TB_TIPO_PESSOA VALUES (NEWID(),'FORNECEDOR');
	INSERT INTO TB_TIPO_PESSOA VALUES (NEWID(),'FUNCIONARIO');
	INSERT INTO TB_TIPO_PESSOA VALUES (NEWID(),'CONSUMIDOR');

	SELECT*FROM TB_TIPO_PESSOA;

CREATE TABLE TB_INF_PESSOA(
	ID			UNIQUEIDENTIFIER PRIMARY KEY,
	NOME		VARCHAR(100),
	SEXO		 CHAR(1) CHECK(SEXO='F' OR SEXO='M'),
	CPF_CNPJ	 VARCHAR(18) UNIQUE,
	ID_TIPO_PESSOA		UNIQUEIDENTIFIER,
	CONSTRAINT ID_TIPO FOREIGN KEY (ID_TIPO_PESSOA) REFERENCES TB_TIPO_PESSOA(ID)
);
	INSERT INTO TB_INF_PESSOA VALUES (NEWID(),'ESTABECIMENTO AGORA',NULL,'123.234.334-34',(SELECT ID FROM TB_TIPO_PESSOA WHERE DESCRICAO ='ESTABELECIMENTO'));
	INSERT INTO TB_INF_PESSOA VALUES (NEWID(),'ESTABECIMENTO DEPOIS',NULL,'111.434.980-12',(SELECT ID FROM TB_TIPO_PESSOA WHERE DESCRICAO ='ESTABELECIMENTO'));
	INSERT INTO TB_INF_PESSOA VALUES (NEWID(),'FORNECEDOR GENERAL LOGIC',NULL,'123.232.692-20',(SELECT ID FROM TB_TIPO_PESSOA WHERE DESCRICAO ='FORNECEDOR'));
	INSERT INTO TB_INF_PESSOA VALUES (NEWID(),'FORNECEDOR JUNDIA',NULL,'1123.234.692-20',(SELECT ID FROM TB_TIPO_PESSOA WHERE DESCRICAO ='FORNECEDOR'));
	INSERT INTO TB_INF_PESSOA VALUES (NEWID(),'CONSUMIDOR JOSE DA SILVA','M','123.025.232-20',(SELECT ID FROM TB_TIPO_PESSOA WHERE DESCRICAO ='FUNCIONARIO'));
	INSERT INTO TB_INF_PESSOA VALUES (NEWID(),'CONSUMIDOR ULIASEE','M','142.744.322-20',(SELECT ID FROM TB_TIPO_PESSOA WHERE DESCRICAO ='CONSUMIDOR'));

	SELECT * FROM TB_INF_PESSOA;


CREATE TABLE TB_ENDERECO(
	ID		UNIQUEIDENTIFIER PRIMARY KEY,
	CEP		CHAR(6),
	RUA		VARCHAR(100),
	NUMERO	VARCHAR(5),
	BAIRRO	VARCHAR(30),
	ID_TIPO_PESSOA UNIQUEIDENTIFIER,
	CONSTRAINT ID_TIPO_END FOREIGN KEY (ID_TIPO_PESSOA) REFERENCES TB_TIPO_PESSOA(ID)
);

CREATE TABLE TB_CONTATO(
	ID			UNIQUEIDENTIFIER PRIMARY KEY,
	NUMERO_TELEFONE	 VARCHAR(14) UNIQUE,
	TEL_ATIVO	 BIT,				 -- TRUE OU FALSE PARA SABER SE O TELEFONE AINDA É USADO
	EMAIL    VARCHAR(50),
	EMAIL_ATIVO BIT,
	NUMERO_CEL VARCHAR(14) UNIQUE,
	ID_TIPO_PESSOA		UNIQUEIDENTIFIER,
	CONSTRAINT ID_TIPO_TEL FOREIGN KEY (ID_TIPO_PESSOA) REFERENCES TB_TIPO_PESSOA(ID)
);


/*=================================================
					PRODUTO
===================================================*/

CREATE TABLE TB_PRODUTOS (
	COD_PRODUTO INT IDENTITY PRIMARY KEY NOT NULL,
    NOME VARCHAR(85),    
    VALOR_UNIT DECIMAL(10,2),
    MARCA VARCHAR(15),
    PRODUTO_TIPO VARCHAR(20)
);
GO

CREATE TABLE TB_ESTOQUE_PRODUTOS (
    COD_ESTOQUE INT IDENTITY(1,1) PRIMARY KEY NOT NULL ,	
	QUANTIDADE INT,     
);
GO
  
/*=================================================
					CONSUMIDOR
===================================================*/

CREATE TABLE TB_CLIENTES(  
	ID_CONSUMIDOR INT  PRIMARY KEY  IDENTITY(1,1)NOT NULL,
	NOME VARCHAR(30) NOT NULL,
    SEXO CHAR NOT NULL,    
    EMAIL VARCHAR(50),    
    USUARIO VARCHAR(16),
    SENHA VARCHAR(20),    
);
GO

 /*=================================================
					FUNCIONARIO
===================================================*/

CREATE TABLE TB_FUNCIONARIOS (
   -- ID_FUNC INT IDENTITY(1,1) PRIMARY KEY NOT NULL,  
    NOME VARCHAR(40) NOT NULL,	
  --  SEXO CHAR NOT NULL,
 --   DATA_DE_NASCIMENTO DATETIME NOT NULL,
  --  CARGO VARCHAR(20) NOT NULL,
    --SALARIO DECIMAL(10,2) NOT NULL,
	--RG VARCHAR (13),
    --CPF VARCHAR(15) NOT NULL,
 
   );
GO
select * from TB_FUNCIONARIOS;
 /*=================================================
				 FORNECEDOR
===================================================*/

CREATE TABLE TB_FORNECEDORES (
	CNPJ_FORNECEDOR INT PRIMARY KEY NOT NULL,
    NOME VARCHAR(25),
    CNPJ VARCHAR(15),
	);
GO

/*=================================================
					COMANDA
===================================================*/

CREATE TABLE TB_COMANDAS (
    NUM_COMANDA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,    
    ID_COMANDA INT NOT NULL,
    VALOR_TOTAL DECIMAL(10,2),   
);
GO
 
/*=================================================
					PEDIDO
===================================================*/

CREATE TABLE TB_PEDIDOS (
    NUM_PEDIDO INT IDENTITY(1,1) PRIMARY KEY, 
    DATA_PEDIDO DATE,
    NOME_PRODUTO VARCHAR(35),
    QUANTIDADE INT,
    VALOR_UNIT DECIMAL(10,2),
 );
GO        

/*=================================================
					HIERARQUIA
===================================================*/

CREATE TABLE TB_NIVERHIERARQUI(
	ID_NH INT PRIMARY KEY IDENTITY(1,1),
	NOME_NH VARCHAR(20)
);
GO

CREATE TABLE TB_LOGINS(
	ID_LOGIN INT PRIMARY KEY IDENTITY(1,1),
	USUARIO VARCHAR(30) UNIQUE NOT NULL,
	SENHA VARCHAR(20) NOT NULL,
	ID_NH INT NOT NULL,
	CONSTRAINT FK_ID_NH FOREIGN KEY (ID_NH) REFERENCES TB_NIVERHIERARQUI(ID_NH)
);
GO
